- name: Install SNMP
  ansible.builtin.apt:
    name: snmpd
    state: present
    update_cache: yes

- name: Configure SNMP
  ansible.builtin.template:
    src: snmpd.conf.j2
    dest: /etc/snmp/snmpd.conf
  notify: restart snmpd

- name: Enable and start SNMP service
  ansible.builtin.service:
    name: snmpd
    enabled: yes
    state: started

- name: Open SNMP port in the firewall
  ansible.builtin.ufw:
    rule: allow
    port: 161
    proto: udp
