- name: Ensure .ssh directory exists
  ansible.builtin.file:
    path: "~/.ssh"
    state: directory
    mode: '0700'

- name: Add SSH key
  ansible.builtin.copy:
    dest: "~/.ssh/authorized_keys"
    content: "{{ ssh_public_key }}"
    mode: '0600'
