- name: Ensure .ssh directory exists
  ansible.builtin.file:
    path: "~/.ssh"
    state: directory
    mode: '0700'

- name: Add SSH key
  ansible.builtin.lineinfile:
    path: "~/.ssh/authorized_keys"
    line: "{{ ssh_public_key }}"
    create: yes
    mode: '0600'
